### ISSUE TITLE
Error MySql

### ISSUE THREAD

**Issue by Cripix** [Bara/Store#4]
Hi, got a problem here.
The plugin doesn't work with the new update on my server ( last commit ). I dunno why, i've tried a few things but nothing works.

L 02/16/2018 - 17:58:55: [SM] Exception reported: Invalid database Handle 1/0 (error: 4)
L 02/16/2018 - 17:58:55: [SM] Blaming: store.smx
L 02/16/2018 - 17:58:55: [SM] Call stack trace:
L 02/16/2018 - 17:58:55: [SM] [0] Database.Driver.get
L 02/16/2018 - 17:58:55: [SM] [1] Line 2131, d:\Cloud\SourcePawn\GitHub\Store\addons\sourcemod\scripting\store.sp::SQLCallback_Connect

**Comment by Bara** [comment]
Possible I'm not done with new syntax update.

Use this version of store: https://github.com/Bara/Store/tree/054c31d52c629c20aa31569f1a6f240769cab8e8

**Comment by Bara** [comment]
@Cripix I've fixed the issue, you could try the latest version now if it works.

**Comment by Cripix** [comment]
Thanks !

I have a new error now:

L 02/16/2018 - 22:15:33: [store.smx] Error happened. Error: Table 'sql3.store_players' doesn't exist

When the database is not created and when she is create I have this error:

L 02/16/2018 - 21:39:29: [store.smx] Error happened. Error:

**Comment by Bara** [comment]
Okay... then use my linked version: https://github.com/Bara/Store/tree/054c31d52c629c20aa31569f1a6f240769cab8e8

current changes aren't tested like you see it..

**Comment by Cripix** [comment]
It's work Thanks.
