### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ninktos** [Bara/Store#5]
After upload this version, I get this error:

[store.smx] Error happened. Error: 

While, ingame i get: Please wait. Your inventory hasn't been fetched yet.

With [this](https://github.com/Bara/Store/tree/054c31d52c629c20aa31569f1a6f240769cab8e8) version, works well.

**Comment by Bara** [comment]
I know, all changes are currently untested. I'll test it with the next commits.

**Comment by Bara** [comment]
After installing this store first time.... I've the message too, but after credits timer it works again.

**Comment by Bara** [comment]
Should be fixed with https://github.com/Bara/Store/commit/31faca26cb92b29da67eae875f9508c3c868ca95
