### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Ninktos** [Bara/Store#6]
After updated to last version i get:

L 02/23/2018 - 21:13:24: [SM] Exception reported: Using two team colors in one message is not allowed
L 02/23/2018 - 21:13:24: [SM] Blaming: store.smx

With [this](https://github.com/Bara/Store/tree/054c31d52c629c20aa31569f1a6f240769cab8e8) version, got no problems.

**Comment by Bara** [comment]
Which colors do you want to use (in one message)?

**Comment by Ninktos** [comment]
Blues and white.
Tried using {default} instead of {white} color, but I didn’t get the nametag color.

**Comment by Caaine** [comment]
this colors are working

{darkblue}
{darkred}
{default}
{green}
{lightgreen}
{olive}
{lime}
{lightred}
{lightblue}
{purple}
{grey}
{yellow}
{orange}
{bluegrey}
{grey2}
{orchid}

**Comment by Bara** [comment]
@Ninktos blue is a team color (try to use darkblue or lightblue). white are undefined on csgo and default should be white too.

**Comment by Ninktos** [comment]
@Caaine Thanks! Also, exists {gold} color.

**Comment by Bara** [comment]
@Ninktos but not with multicolors/colors.inc https://github.com/Bara/Store/blob/master/addons/sourcemod/scripting/include/multicolors/colors.inc
